AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a basic secure network environmet
Parameters:
  Env:
    Description: The type of environment
    Type: String
    AllowedValues:
    - dev
    - sys
    - test
    - perf
    - prod
    
  VPCCidrBlock:
    Description: Cidr Block for the VPC
    Type: String
    Default: 10.0.0.0/16

Resources:
  VirtualPrivateCloud:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
      - Key: Env
        Value: !Ref Env

Outputs:
  VPCCidrBlock:
    Description: CidrBlock for the VPC
    Value: 
      !GetAtt VirtualPrivateCloud.CidrBlock
    Export:
      Name: VPCCidrBlock
      
  VPCID:
    Description: CidrBlock for the VPC
    Value: 
      !Ref VirtualPrivateCloud
    Export:
      Name: VPCID
