AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
#Parameters:
#  FilePath:
#    Description: The path of the  file.
#    Type: String
#    Default: /home/ec2-user/userdata

Resources:
  VirtualPrivateCloud:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default

Outputs:
  VPCCidirBlock:
    Description: CidrBlock for the VPC
    Value: 
       Fn::GetAtt:VirtualPrivateCloud.CidrBlock
    Export:
      Name: VPCCidirBlock