AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a basic secure network environmet
Parameters:
  Env:
    Description: The type of environment
    Type: String
    AllowedValues:
    - dev
    - sys
    - test
    - perf
    - prod
    
  VPCCidrBlock:
    Description: Cidr Block for the VPC
    Type: String
    Default: 10.0.0.0/16
    
  PrivateSubnet1CidrBlock:
    Description: Cidr Block for the Private Subnet
    Type: String
    Default: 10.0.1.0/24
    
  PublicSubnet1CidrBlock:
    Description: Cidr Block for the Public Subnet
    Type: String
    Default: 10.0.2.0/24

Resources:
  VirtualPrivateCloud:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: false
      InstanceTenancy: default
      Tags:
      - Key: Env
        Value: !Ref Env
      - Key: Name
        Value: !Sub VPC-${Env} 

     
               
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      #AvailabilityZone: String
      CidrBlock: !Ref PrivateSubnet1CidrBlock
      MapPublicIpOnLaunch: false
      VpcId: !Ref VirtualPrivateCloud
      Tags:
      - Key: Env
        Value: !Ref Env
      - Key: Name
        Value: !Sub PrivateSubnet1-${Env}   

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      #AvailabilityZone: String
      CidrBlock: !Ref PublicSubnet1CidrBlock
      MapPublicIpOnLaunch: false
      VpcId: !Ref VirtualPrivateCloud
      Tags:
      - Key: Env
        Value: !Ref Env
      - Key: Name
        Value: !Sub PublicSubnet1-${Env}        

Outputs:
  VPCCidrBlock:
    Description: CidrBlock for the VPC
    Value: 
      !GetAtt VirtualPrivateCloud.CidrBlock
    Export:
      Name: VPCCidrBlock
      
  VPCID:
    Description: VPC ID for the VPC
    Value: 
      !Ref VirtualPrivateCloud
    Export:
      Name: VPCID
      
  PrivateSubnet1ID:
    Description: Subnet ID for PrivateSubnet1
    Value: 
      !Ref PrivateSubnet1
    Export:
      Name: PrivateSubnet1ID
      
  PublicSubnet1ID:
    Description: Subnet ID for PublicSubnet1
    Value: 
      !Ref PublicSubnet1
    Export:
      Name: PublicSubnet1ID
